### ISSUE TITLE
error in 1.15 Era

### ISSUE THREAD

**Issue by lvangh** [iambz00/Saved#5]
gettign this erorr on 1.15 classic era
Message: Interface/AddOns/SavedClassic/SavedClassic.lua:364: attempt to perform arithmetic on field '?' (a boolean value)
Time: Sun Nov 19 16:59:04 2023
Count: 2
Stack: Interface/AddOns/SavedClassic/SavedClassic.lua:364: attempt to perform arithmetic on field '?' (a boolean value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/SavedClassic/SavedClassic.lua"]:364: in function `SaveChoronoBuff'
[string "@Interface/AddOns/SavedClassic/SavedClassic.lua"]:354: in function `SaveWorldBuff'
[string "@Interface/AddOns/SavedClassic/SavedClassic.lua"]:290: in function `?'
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: 
Message: Interface/AddOns/SavedClassic/SavedClassic.lua:364: attempt to perform arithmetic on field '?' (a boolean value)
Time: Sun Nov 19 17:00:13 2023
Count: 6
Stack: Interface/AddOns/SavedClassic/SavedClassic.lua:364: attempt to perform arithmetic on field '?' (a boolean value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/SavedClassic/SavedClassic.lua"]:364: in function `SaveChoronoBuff'
[string "@Interface/AddOns/SavedClassic/SavedClassic.lua"]:354: in function `SaveWorldBuff'
[string "@Interface/AddOns/SavedClassic/SavedClassic.lua"]:434: in function `ShowInstanceInfo'
[string "@Interface/AddOns/SavedClassic/SavedClassic.lua"]:424: in function `ShowInfoTooltip'
[string "@Interface/AddOns/SavedClassic/SavedClassic.lua"]:558: in function <Interface/AddOns/SavedClassic/SavedClassic.lua:548>

Locals:

**Comment by iambz00** [comment]
Fixed.
Now it need +16 instead of +15
