### ISSUE TITLE
Locale "Vault of Archavon" bug

### ISSUE THREAD

**Issue by roxasgaming** [iambz00/Saved#7]
If the character has a saved "Vault of Archavon", the addon's table suddenly stop working.

The error message generated is the following:
`Message: Interface/AddOns/SavedClassic/SavedClassic.lua:935: attempt to index field '?' (a nil value)
Time: Mon Feb 19 10:07:11 2024
Count: 3
Stack: Interface/AddOns/SavedClassic/SavedClassic.lua:935: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/SavedClassic/SavedClassic.lua"]:935: in function <Interface/AddOns/SavedClassic/SavedClassic.lua:934>
[string "=[C]"]: in function 'sort'
[string "@Interface/AddOns/SavedClassic/SavedClassic.lua"]:934: in function 'ToggleRaidTable'
[string "@Interface/AddOns/SavedClassic/SavedClassic.lua"]:822: in function <Interface/AddOns/SavedClassic/SavedClassic.lua:819>`

This bug is found with the spanish language. Anonther extra info that should be useful is the next error trace:
`Locals: a = "CÃ¡mara de Archavon"
b = "Naxxramas"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"`

The real name in spanish is "Cámara de Archavon", so this is probably related to the bug reason.

**Comment by iambz00** [comment]
It seems that Blizzard changed zone name or instance name of 'Vault of Archavon'.
Stealth patch. as always.
Thank you.

**Comment by iambz00** [comment]
Cured
2e4c00286d33966ae1fbd1cfd758a9a7d5d78f73(3.4.3)

**Comment by iambz00** [comment]
Cured
2e4c00286d33966ae1fbd1cfd758a9a7d5d78f73(3.4.3)
